const billProducts = [
  {
    ID: 1,
    Producto: 'Computadora portátil',
    Precio: 1200,
    Cantidad: 10,
    Total: 1200 * 10,
  },
  {
    ID: 2,
    Producto: 'Mouse inalámbrico',
    Precio: 25,
    Cantidad: 50,
    Total: 25 * 50,
  },
  {
    ID: 3,
    Producto: 'Teclado mecánico',
    Precio: 70,
    Cantidad: 30,
    Total: 70 * 30,
  },
  {
    ID: 4,
    Producto: 'Monitor 24 pulgadas',
    Precio: 150,
    Cantidad: 20,
    Total: 150 * 20,
  },
  {
    ID: 5,
    Producto: 'Disco duro externo 1TB',
    Precio: 60,
    Cantidad: 40,
    Total: 60 * 40,
  },
  {
    ID: 6,
    Producto: 'Impresora multifunción',
    Precio: 200,
    Cantidad: 15,
    Total: 200 * 15,
  },
  {
    ID: 7,
    Producto: 'Altavoces Bluetooth',
    Precio: 45,
    Cantidad: 25,
    Total: 45 * 25,
  },
  {
    ID: 8,
    Producto: 'Webcam HD',
    Precio: 35,
    Cantidad: 30,
    Total: 35 * 30,
  },
  {
    ID: 9,
    Producto: 'Micrófono USB',
    Precio: 80,
    Cantidad: 20,
    Total: 80 * 20,
  },
  {
    ID: 10,
    Producto: 'Tablet 10 pulgadas',
    Precio: 300,
    Cantidad: 18,
    Total: 300 * 18,
  },
];
